# Generated by Django 3.1.1 on 2020-09-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('desc', models.CharField(choices=[('location', 'Unable to find a location'), ('methodology', 'Questions about methodology'), ('else', 'Something else')], max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
