# Generated by Django 3.1.1 on 2020-09-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeboardConstructionCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('floodzone', models.CharField(max_length=100)),
                ('parish', models.CharField(max_length=100)),
                ('no_floors', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(max_length=122),
        ),
    ]
