# Generated by Django 3.1.2 on 2020-10-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootApp', '0002_auto_20200914_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sampledata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('floodzone', models.CharField(max_length=100)),
                ('parish', models.CharField(max_length=100)),
                ('no_floors', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='freeboardconstructioncost',
            name='no_floors',
            field=models.CharField(max_length=10),
        ),
    ]
